org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

mc_version=1.21.1
neo_version=21.1.248

mekanism_version=1.21.1-10.7.19.85
gtm_version=7.0.2
ldlib2_version=2.2.37
configuration_version=3.1.1
registrate_version=1.4.8

mod_id=gregified_mekanism
mod_name=gregified_mekanism
mod_license=GNU LGPL 3.0
mod_version=1.0-alpha
mod_group_id=vimusienko
mod_authors=MeowmelMuku, ViMusienko.
mod_description=Интеграция обработки руд между GTCEu Modern и Mekanism.